runtime: python39
instance_class: F4_1G

vpc_access_connector:
  name: projects/fast-ai-exploration/locations/us-west2/connectors/clip

env_variables:
  REDISHOST: '10.31.145.115'
  REDISPORT: '6379'

handlers:
- url: /.*
  secure: always
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 1
  max_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
