runtime: python39 # or another supported version

instance_class: F4_1G

handlers:
- url: /.*
  secure: always
  script: auto

env_variables:
  PIXABAY_API_KEY: ${PIXABAY_API_KEY}

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
