name: Deploy an App Engine app

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@v0.1.0
      - name: Set up AppEngine deployer.
        with:
          project: ${{ secrets.gcp_project }}
          deliverables: app.yaml
          credentials: ${{ secrets.gcp_credentials }}
