name: Deploy an App Engine app

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    outputs:
      string: ${{ steps.changestring.outputs.string}}

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.gcp_credentials }}
          export_default_credentials: true      
      - uses: google-github-actions/deploy-appengine@main
        with:
          working_directory: server
          project_id: ${{ secrets.gcp_project }}
          deliverables: app.yaml
