name: Deploy an App Engine app

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    outputs:
      string: ${{ steps.changestring.outputs.string}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up AppEngine deployer.
        uses: google-github-actions/deploy-appengine@v0.1.0
        with:
          project: ${{ secrets.gcp_project }}
          deliverables: app.yaml
          credentials: ${{ secrets.gcp_credentials }}
